canary/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('urlshortener.urls')),
]

urlshortener/urls.py
from django.conf.urls import url

from . import views

app_name = 'urlshortener'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<short_string>\w+)$', views.redirect, name = 'redirect')
]

urlshortener/models.py
import random, string

from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings

class LinkManager(models.Manager):
    def find_or_create(self, base_url):
        result = self.get_queryset().filter(base_url = base_url)
        if result.exists():
            link = result.first()
        else:
            link = self.model(base_url = base_url)
            link.generate_short_string()
            link.save()
        return link

class Link(models.Model):
    base_url = models.CharField('Base URL', max_length=256, unique=True)
    short_string = models.CharField(max_length=30, unique=True)

    objects = LinkManager()

    def __str__(self):
        return str({'id': self.id, 'short_url': self.short_url()})

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Link, self).save(*args, **kwargs)

    def short_url(self):
        return "%s%s" % (settings.DOMAIN, self.short_string)

    def generate_short_string(self, length=6, charset=string.ascii_letters + string.digits):
        randomize = lambda: ''.join(random.SystemRandom().choice(charset) for i in range(length))
        rand_str = randomize()
        while Link.objects.filter(short_string = rand_str).exists():
            rand_str = randomize()
        self.short_string = rand_str

urlshortener/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic

from .models import Link

def index(request):
    if request.method == 'GET':
        return render(request, 'urlshortener/index.html')
    else:
        link = Link.objects.find_or_create(request.POST['url'])
        return render(request, 'urlshortener/index.html', {'link': link})

def redirect(request, short_string):
    link = get_object_or_404(Link, short_string = short_string)
    return HttpResponseRedirect(link.base_url)

urlshortener/templates/urlshortener/index.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'urlshortener/style.css' %}" type="text/css" />

<div class="container">
  <div class="content">
    <h1>URL Shortener</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'urlshortener:index' %}" method="post">
      {% csrf_token %}
      <label for="url">Enter long URL below</label>
      <br />
      <input type="text", name="url" />
      <input type="submit" value="Shorten">
    </form>

    {% if link %}
      <p>Long URL: {{ link.base_url }}</p>
      <p>The short URL for this link is <a href="{{ link.base_url }}" target="_blank">{{ link.short_url }}</a></p>
    {% endif %}
  </div>
</div>